# Generated by Django 5.2.7 on 2025-10-22 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre o número del animal', max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('H', 'Hembra'), ('M', 'Macho'), ('D', 'Desconocido')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('estado_actual', models.CharField(max_length=100)),
                ('foto_animal', models.ImageField(blank=True, null=True, upload_to='img_animales/')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
            },
        ),
        migrations.CreateModel(
            name='Eventos_Sanitarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tratamiento', models.CharField(max_length=200)),
                ('evento', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=50)),
                ('veterinario', models.CharField(max_length=100)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_sanitarios', to='app_granja_vacas.animal')),
            ],
            options={
                'verbose_name': 'Evento Sanitario',
                'verbose_name_plural': 'Eventos Sanitarios',
            },
        ),
    ]
